server:
  port: 8080

app:
  frontend:
    url: http://localhost:5173 # Change this based on your frontend port

spring:
  application:
    name: imdb

  datasource:
    url: jdbc:mysql://localhost:3306/imdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: thinhtranhan21@gmail.com
    password: alna lybp vjkr ccor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: info

jwt:
  secret: W+BZWL5dyk9IuuHE7UEv439DaujnXZ5UfUSOgxGtKEIO6xXo0aubhOnKsFmxZyktysCO9pAUCGNoE9zBbL6SNg==
  expiration: 86400000

imdb:
  pagination:
    default-size: 20
    max-size: 100

tmdb:
  api-key: ${TMDB_API_KEY:tungdv21}
  base-url: https://api.themoviedb.org/3
